# Generated by Django 6.0.7 on 2026-07-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_bookings_options_alter_bookings_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dnt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
