# Generated by Django 6.0.7 on 2026-07-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event_dnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Expired Event',
                'verbose_name_plural': 'Expired Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.event',),
        ),
        migrations.AlterField(
            model_name='event',
            name='dnt',
            field=models.DateTimeField(),
        ),
    ]
